"""empty message

Revision ID: 1bacb4e04394
Revises: 0be6d93dca0d
Create Date: 2020-08-29 11:51:50.747338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bacb4e04394'
down_revision = '0be6d93dca0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colloct',
    sa.Column('me_uid', sa.Integer(), nullable=False),
    sa.Column('co_wid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('me_uid', 'co_wid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colloct')
    # ### end Alembic commands ###
