"""empty message

Revision ID: 24128afd5648
Revises: fa7c0dab146b
Create Date: 2020-08-25 20:33:50.735553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24128afd5648'
down_revision = 'fa7c0dab146b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
