"""empty message

Revision ID: 3efa542ddd6b
Revises: 24128afd5648
Create Date: 2020-08-25 21:04:58.294371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efa542ddd6b'
down_revision = '24128afd5648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'filename')
    # ### end Alembic commands ###
