"""empty message

Revision ID: 9a8c5f5ce8f3
Revises: 1bacb4e04394
Create Date: 2020-08-29 11:59:19.111983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8c5f5ce8f3'
down_revision = '1bacb4e04394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colloct', sa.Column('is_co', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colloct', 'is_co')
    # ### end Alembic commands ###
